# -*- coding: utf-8 -*-
"""Atividade_05_ciência_de_dados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10ZZ9V2SfLl63gbC5UENaMfJX7wy9RKHK
"""

import pandas as pd
df = pd.read_csv('/content/Vendasloja - Vendasloja(1).csv')
print(df)

df.head()   #mostrar as  1 linhas
df.tail()   #mostra as ultimas linhas
df.shape    #mostar tamanho da tabela
df.columns   #mostar nome das colunas
df.info()    #informacao da tabela,numero de linhas, colunas, qual tipo de dados

# mostar as  1 linhas
df.head(10)
df.head(8)

df.sample(3)

#mostar colunas
df["Produto"]
df[["Produto", "Categoria"]]
df[["Produto", "Categoria","Preço"]]

#Estatísticas




df["Preço"].max() #maior valor
df["Preço"].min()  #menor valor


df["Preço"].sum()  #soma

df["Preço"].mean()  #média

df["Preço"].max() #maior valor

df["Preço"].min()  #menor valor

df["Preço"].sum()  #soma

#ordenar dados

df.sort_values("Preço") #ordem crescente
df.sort_values("Preço", ascending=False)

#criar nova coluna

df["Desconto"] = df["Preço"] * 0.10

#salvando as alterações
df.to_csv("Vendasloja_novo.csv", index=False)